### ISSUE TITLE
Java.lang.RuntimeException: Could not generate DH keypair

### ISSUE THREAD

**Issue by kaystrobach** [bsideup/IDEA-GitLab-Integration#13]
![2015-06-15_19-13-32](https://cloud.githubusercontent.com/assets/1185776/8165725/0192de1e-1393-11e5-8ed1-c2c22c860148.png)

I assume due to the fixes which are made in gitlab omnibus due to the logjam vulnerability there is a problem opening the ssl connection ... any idea how to fix this, i assume there is the possibility to change some params in the http(s) initiation code to get this working smoothly

**Comment by bsideup** [comment]
@kaystrobach I'm really sorry, haven't received any notifications :( 

Anyway, I think your issue is not related to this plugin, but built-in Git plugin in IntelliJ IDEA. This one provides option to open file on GitLab's web UI.
