### ISSUE TITLE
Short Documentation how to use

### ISSUE THREAD

**Issue by suther** [bsideup/IDEA-GitLab-Integration#15]
Would be great if you could make a short HowTo-Use Documentation for this Plugin.
Maybe with a short Video (with http://www.screencast-o-matic.com/ it's easy).

**Comment by sciamannikoo** [comment]
+1

**Comment by fabienfeat** [comment]
+1

**Comment by kataloo** [comment]
+1

**Comment by jamc92** [comment]
+1

**Comment by fcools** [comment]
+1

**Comment by suther** [comment]
This plugin seems nothing to do, but only open the current file "on the GitLab-Page" in a Browser-Window.
Maybe better try the other GitLab-Plugin you'll found in Plugin-Repository: Gitlab Integration Plugin (from diogo.sousa.neves)

**Comment by fcools** [comment]
I already suspected I used the other plugin before, but this one was rated higher for some reason. 

Anyway... I'm gonna switch over.
