### ISSUE TITLE
Import Tasks from Gitolite

### ISSUE THREAD

**Issue by theWeird** [bsideup/IDEA-GitLab-Integration#4]
I really like your work on a plugin which connects IDEA to GitLab.
The most imortant feature I loved while working with Redmine was the Connection to my task lists.

Can you add something like this in your plugin?

Maybe you could also use informations like the gitlab user and the checked out branch e.g. to show the task list sorted by users tasks, branch tasks and all tasks.

**Comment by bsideup** [comment]
Task tracking is out of scope of this plugin, so I close this issue. Sorry.
